# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QMessageBox
import sys
from PyQt5.QtCore import QDate, Qt
from docx import Document

document = Document('解除（终止）劳动关系证明.docx')

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 680)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/.ico/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")

        self.horizontalLayout.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setMaxLength(18)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 8)
        self.horizontalLayout.setStretch(3, 2)
        self.horizontalLayout.setStretch(4, 8)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setDate(QDate.currentDate())
        self.horizontalLayout_2.addWidget(self.dateEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setMaxLength(1)
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 8)
        self.horizontalLayout_2.setStretch(3, 2)
        self.horizontalLayout_2.setStretch(4, 8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit_2.setDate(QDate.currentDate())
        self.horizontalLayout_3.addWidget(self.dateEdit_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.dateEdit_3.setDate(QDate.currentDate())
        self.horizontalLayout_3.addWidget(self.dateEdit_3)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 8)
        self.horizontalLayout_3.setStretch(3, 2)
        self.horizontalLayout_3.setStretch(4, 8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setSizeIncrement(QtCore.QSize(30, 30))
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setMaxVisibleItems(15)
        self.comboBox.setIconSize(QtCore.QSize(16, 16))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.dateEdit_4 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.dateEdit_4.setDate(QDate.currentDate())
        self.horizontalLayout_4.addWidget(self.dateEdit_4)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 8)
        self.horizontalLayout_4.setStretch(3, 2)
        self.horizontalLayout_4.setStretch(4, 8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")

        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.dateEdit_5 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_5.setObjectName("dateEdit_5")
        self.dateEdit_5.setDate(QDate.currentDate())
        self.horizontalLayout_5.addWidget(self.dateEdit_5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.dateEdit_6 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_6.setObjectName("dateEdit_6")
        self.dateEdit_6.setDate(QDate.currentDate())
        self.horizontalLayout_5.addWidget(self.dateEdit_6)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 8)
        self.horizontalLayout_5.setStretch(3, 2)
        self.horizontalLayout_5.setStretch(4, 8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.all_submit)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "姓名"))
        self.label_3.setText(_translate("MainWindow", "身份证号码"))
        self.label_4.setText(_translate("MainWindow", "入职时间"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.label_5.setText(_translate("MainWindow", "签订年限"))
        self.label_6.setText(_translate("MainWindow", "合同时间"))
        self.dateEdit_2.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.label_8.setText(_translate("MainWindow", "结束合同时间"))
        self.dateEdit_3.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.label_9.setText(_translate("MainWindow", "离职原因"))
        self.comboBox.setItemText(0, _translate("MainWindow", "个人原因"))
        self.comboBox.setItemText(1, _translate("MainWindow", "自身学习与发展"))
        self.comboBox.setItemText(2, _translate("MainWindow", "工作家庭无法平衡"))
        self.comboBox.setItemText(3, _translate("MainWindow", "工作岗位与预想不同"))
        self.comboBox.setItemText(4, _translate("MainWindow", "工作地点和环境"))
        self.comboBox.setItemText(5, _translate("MainWindow", "公司福利不好"))
        self.comboBox.setItemText(6, _translate("MainWindow", "工作时间太长\\压力大"))
        self.comboBox.setItemText(7, _translate("MainWindow", "管理方式"))
        self.label_11.setText(_translate("MainWindow", "提出出离职日期"))
        self.dateEdit_4.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.label_12.setText(_translate("MainWindow", "决定离职日期"))
        self.dateEdit_5.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.label_13.setText(_translate("MainWindow", "盖章日期"))
        self.dateEdit_6.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.pushButton.setText(_translate("MainWindow", "提交"))


    def all_submit(self):
        # 姓名
        name = self.lineEdit.text().strip()
        # 身份证号
        uid = self.lineEdit_2.text()
        # 入职时间，年、月、日
        rn, ry, rr = self.dateEdit.date().toString(Qt.ISODate).split('-')

        # 签订年限
        nx = self.lineEdit_3.text()
        # 合同时间
        sn, sy, sr = self.dateEdit_2.date().toString(Qt.ISODate).split('-')
        # 合同结束时间
        jn, jy, jr = self.dateEdit_3.date().toString(Qt.ISODate).split('-')
        # 离职原因
        yy = self.comboBox.currentText()
        # 提成离职时间
        tn, ty, tr = self.dateEdit_4.date().toString(Qt.ISODate).split('-')
        # 决定离职时间
        gn, gy \
            , gr = self.dateEdit_4.date().toString(Qt.ISODate).split('-')
        # 盖章时间
        dqn, dqy, dqr = self.dateEdit_4.date().toString(Qt.ISODate).split('-')
        data = {
            'name': name,
            'uid': uid,
            'rn': rn,
            'ry': ry,
            'rr': rr,
            'nx': nx,
            'sn': sn,
            'sy': sy,
            'sr': sr,
            'jn': jn,
            'jy': jy,
            'jr': jr,
            'yy': yy,
            'tn': tn,
            'ty': ty,
            'tr': tr,
            'gn': gn,
            'gy': gy,
            'gr': gr,
            'dqn': dqn,
            'dqy': dqy,
            'dqr': dqr,
        }
        all_para = document.paragraphs
        for para in all_para:
            for run in para.runs:
                for k, v in data.items():
                    if k in run.text:  # 判断是否存在
                        run.text = run.text.replace(k, v)
        document.save(f'{name}.docx')
        document.exit()




import imgr_rc

if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
