# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QMainWindow,QMessageBox
import prc_rc
import sys
import os
import shutil
import pyperclip
import datetime,time
import xlwings as xw
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(716, 368)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(35, 35))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(300, 120, 75, 40))
        self.pushButton_12.setObjectName("pushButton_12")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 671, 101))
        self.widget.setMinimumSize(QtCore.QSize(75, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_1.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setEnabled(True)
        self.pushButton.setMinimumSize(QtCore.QSize(75, 40))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_1.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(75, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_1.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(75, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_1.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(75, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_1.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(75, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_1.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(75, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_1.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(75, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_1.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(75, 40))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_1.addWidget(self.pushButton_8)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 120, 281, 51))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_9.setMinimumSize(QtCore.QSize(75, 40))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_2.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_10.setMinimumSize(QtCore.QSize(75, 40))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_11.setMinimumSize(QtCore.QSize(75, 40))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_2.addWidget(self.pushButton_11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 716, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_12.clicked.connect(MainWindow.close)
        self.pushButton.clicked.connect(self.jishi)
        self.pushButton_2.clicked.connect(self.openjishibiao)
        self.pushButton_3.clicked.connect(self.delete_zz)
        self.pushButton_3.clicked.connect(self.delete_lz)
        self.pushButton_5.clicked.connect(self.openfxb)
        self.pushButton_6.clicked.connect(self.openhz)
        self.pushButton_7.clicked.connect(self.openpychram)
        self.pushButton_8.clicked.connect(self.openchrom)
        self.pushButton_9.clicked.connect(self.copyje)
        self.pushButton_10.clicked.connect(self.opencz)
        self.pushButton_11.clicked.connect(self.openye)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def jishi(self):
        path = r'\\zff-\德诚竞价部共享\01-流量即时效果经营'
        for filepath, filename, name in os.walk(path):
            for x in name:
                os.remove(os.path.join(filepath, x))
        paths = r'D:\竞价即时'
        for filepath, filename, name in os.walk(paths):
            num = 0
            for x in name:
                num += 1
                shutil.move(os.path.join(filepath, x), os.path.join(path, x))
    def openjishibiao(self):
        try:
            os.startfile(r'\\zff-\德诚竞价部共享\01-流量即时效果经营-升级版 .xlsm')
        except:
            QMessageBox.information(MainWindow,'消息','被占用了', QMessageBox.Yes | QMessageBox.No,QMessageBox.Yes)

    def delete_zz(self):
        path=r'\\zff-\德诚竞价部共享\02-花名册在职员工'
        for filepath, filename, name in os.walk(path):
            for x in name:
                os.remove(os.path.join(filepath, x))
    def delete_lz(self):
        path=r'\\zff-\德诚竞价部共享\02-花名册离职员工'
        for filepath, filename, name in os.walk(path):
            for x in name:
                os.remove(os.path.join(filepath, x))
    def openfxb(self):
        try:
            os.startfile(r'\\zff-\德诚竞价部共享\02-流量方向效果经营-5次升级版.xlsm')
        except:
            QMessageBox.information(MainWindow,'消息','被占用了', QMessageBox.Yes | QMessageBox.No,QMessageBox.Yes)

    def openhz(self):
        try:
            os.startfile(r'C:\Users\ASUS\PycharmProjects\dg\汇总.xlsx')
        except:
            QMessageBox.information(MainWindow, '消息', '被占用了', QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
    def openpychram(self):
        os.startfile(r'D:\Pycharm_Professional_2021.2.1_Protable\Pycharm_Professional_2021.2.1_Protable\bin\pycharm64.exe')
    def openchrom(self):
        os.startfile(r'C:\Users\ASUS\AppData\Local\Google\Chrome\Application\chrome.exe')
    def copyje(self):
        wenben="""
    推广总充值费用： 元；
    广州入户，合计充值：；
            
    温馨的提示：
    1、具体怎么充值账号，见附件。
    """
        pyperclip.copy(wenben)
    def opencz(self):
        y=datetime.datetime.now().month
        r=datetime.datetime.now().day
        path=rf'D:\充值表\{y}月{r}日充值指引.xlsx'
        xw.App(visible=True, add_book=False)
        abc = xw.books.add()
        abc.save(path)  # 指定文件存放路径
        abc.close()
        time.sleep(1)
        try:
            if os.path.isfile(path):
                os.startfile(path)
            else:
                pass
        except:
            QMessageBox.information(MainWindow, '消息', '被占用了', QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
    def openye(self):
        try:
            os.startfile(r'\\zff-\德诚竞价部共享\03-2021年账户余额及充值管理表(修改版).xlsx')
        except:
            QMessageBox.information(MainWindow, '消息', '被占用了', QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_12.setText(_translate("MainWindow", "退出"))
        self.pushButton.setText(_translate("MainWindow", "删除即时表"))
        self.pushButton_2.setText(_translate("MainWindow", "打开即时表"))
        self.pushButton_3.setText(_translate("MainWindow", "删除在职"))
        self.pushButton_4.setText(_translate("MainWindow", "删除离职"))
        self.pushButton_5.setText(_translate("MainWindow", "打开方向表"))
        self.pushButton_6.setText(_translate("MainWindow", "打开汇总表"))
        self.pushButton_7.setText(_translate("MainWindow", "打开pychram"))
        self.pushButton_8.setText(_translate("MainWindow", "打开游览器"))
        self.pushButton_9.setText(_translate("MainWindow", "复制充值语句"))
        self.pushButton_10.setText(_translate("MainWindow", "打开充值表格"))
        self.pushButton_11.setText(_translate("MainWindow", "打开充值余额表"))

if __name__ == '__main__':
    app=QApplication(sys.argv)
    MainWindow=QMainWindow()
    ui =Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())